server:
  port: 84

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/loltrial
    username: root
    password: 1234

openapi:
  serviceKey: SCT/cM3T6lehlLW/rcMn+TwXDTh7t5JRN3+iIdSXGPQ6rdEJmCNKQQa0LoMlMslQBptdg4Dt1BgX0pJ9o+h2kg==
  baseUrl: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtFcst